# What is PyTorch

PyTorch는 두 가지 높은 수준의 기능을 제공하는 python 패키지입니다.

- 강력한 GPU 가속을 사용하는 텐서 계산 (numpy 같은) - Tensor computation (like numpy) with strong GPU acceleration
- 테이프 기반 자동 시작 시스템에 구축 된 딥 뉴럴 네트워크 - Deep Neural Networks built on a tape-based autograd system



numpy, scipy 및 Cython과 같이 자주 사용되는 파이썬 패키지를 재사용하여 필요할 때 PyTorch를 확장 할 수 있습니다.

세분화 된 수준에서 PyTorch는 다음 구성 요소로 구성된 라이브러리입니다.

You can reuse your favorite python packages such as numpy, scipy and Cython to extend PyTorch when needed.

At a granular level, PyTorch is a library that consists of the following components:

![pytorch package](./pytorch_packages.png)


일반적으로 PyTorch는 다음 중 하나를 사용합니다.

- GPU의 성능을 사용하기 위해 numpy로 대체되었습니다.
- 최대한의 유연성과 속도를 제공하는 심층 학습 연구 플랫폼

## Getting Started

### Tensor
Tensors는 numpy의 ndarrays와 유사하며 Tensors를 컴퓨팅 가속화를 위해 GPU에서도 사용할 수 있습니다.

초기화되지 않은 5x3 행렬을 만듭니다.

In [1]:
import torch

x = torch.Tensor(5, 3)
print(x)


1.00000e-35 *
  0.0000  0.0000  0.0000
  0.0000  0.0004  0.0000
  0.0073  0.0000  0.0073
  0.0000  0.0004  0.0000
  0.2297  0.0000  1.6572
[torch.FloatTensor of size 5x3]



무작위로 초기화 된 행렬 생성

In [2]:
x = torch.rand(5, 3)
print(x)


 0.8566  0.3620  0.6656
 0.0115  0.1039  0.1780
 0.2518  0.4735  0.4636
 0.9745  0.6100  0.3553
 0.5997  0.6037  0.4795
[torch.FloatTensor of size 5x3]



Get its size

In [3]:
print(x.size())

torch.Size([5, 3])


### Operations
There are multiple syntaxes for operations. Let's see addition as an example

조작을위한 구문은 여러 가지가 있습니다. 추가 사항을 예제로 보자.

Addition: syntax1

In [4]:
y = torch.rand(5, 3)
print(x + y)


 1.4004  1.2056  1.2658
 0.9867  0.9890  0.5695
 0.3306  0.7555  0.7920
 1.8020  1.3032  0.7287
 1.4401  1.2855  0.6033
[torch.FloatTensor of size 5x3]



Addtion: syntax2

In [5]:
print(torch.add(x, y))


 1.4004  1.2056  1.2658
 0.9867  0.9890  0.5695
 0.3306  0.7555  0.7920
 1.8020  1.3032  0.7287
 1.4401  1.2855  0.6033
[torch.FloatTensor of size 5x3]



Addtion: giving an output tensor

In [6]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.4004  1.2056  1.2658
 0.9867  0.9890  0.5695
 0.3306  0.7555  0.7920
 1.8020  1.3032  0.7287
 1.4401  1.2855  0.6033
[torch.FloatTensor of size 5x3]



Addition: in-place

In [7]:
# adds x to y
y.add_(x)
print(y)


 1.4004  1.2056  1.2658
 0.9867  0.9890  0.5695
 0.3306  0.7555  0.7920
 1.8020  1.3032  0.7287
 1.4401  1.2855  0.6033
[torch.FloatTensor of size 5x3]



You can use standard numpy-like indexing with all bells and whistles!

In [8]:
print(x[:, 1])


 0.3620
 0.1039
 0.4735
 0.6100
 0.6037
[torch.FloatTensor of size 5]



## Numpy Bridge


토치 텐서를 수적으로 배열로 변환하거나 그 반대로 변환하는 것은 쉽습니다. 


토치 Tensor와 numpy 배열은 기본 메모리 위치를 공유 할 것이고 하나를 변경하면 다른 메모리가 변경됩니다. 

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### Converting torch Tensor to numpy Array

In [9]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [10]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


See how the numpy array changed in value.

In [11]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


### Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically.

In [12]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

